Repository mustafa99557/c-language-, pull requests merged in 2025-10, with the labels that each got.

#11 Create modified postfix.c
  modified postfix.c
Labels: hacktoberfest-accepted

#13 Create modifiedMatrixaddition.c
  modifiedMatrixaddition.c
  modifiesCqueue.c
Labels: help wanted, good first issue, hacktoberfest-accepted

#16 Create concatinated2.c
  concatinated.c
Labels: hacktoberfest-accepted

#17 Create insertion1.c
  insertion.c
  selection.c
Labels: good first issue, hacktoberfest-accepted
